"""added u_id in user model and made password unique constraint

Revision ID: 60e21aad92b4
Revises: 0cd4a320d62e
Create Date: 2022-12-11 23:24:02.378847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e21aad92b4'
down_revision = '0cd4a320d62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_id', sa.String(length=20), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint('user_password_key', type_='unique')
        batch_op.create_unique_constraint(None, ['u_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_password_key', ['password'])
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('u_id')

    # ### end Alembic commands ###
